# Generated by Codex on 2026-05-29

import uuid

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone

from plane.db.models.lark import generate_lark_job_id


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("db", "0121_alter_estimate_type"),
    ]

    operations = [
        migrations.AlterField(
            model_name="account",
            name="provider",
            field=models.CharField(choices=[("google", "Google"), ("github", "Github"), ("gitlab", "GitLab"), ("lark", "Lark")]),
        ),
        migrations.CreateModel(
            name="LarkEvent",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True, verbose_name="Created At")),
                ("updated_at", models.DateTimeField(auto_now=True, verbose_name="Last Modified At")),
                ("created_by", models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="%(class)s_created_by", to=settings.AUTH_USER_MODEL, verbose_name="Created By")),
                ("updated_by", models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="%(class)s_updated_by", to=settings.AUTH_USER_MODEL, verbose_name="Last Modified By")),
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True, db_index=True)),
                ("deleted_at", models.DateTimeField(blank=True, null=True, verbose_name="Deleted At")),
                ("event_id", models.CharField(db_index=True, max_length=255, unique=True)),
                ("event_type", models.CharField(db_index=True, max_length=255)),
                ("tenant_key", models.CharField(blank=True, db_index=True, max_length=255, null=True)),
                ("payload", models.JSONField(default=dict)),
                ("status", models.CharField(choices=[("pending", "Pending"), ("processing", "Processing"), ("processed", "Processed"), ("failed", "Failed")], db_index=True, default="pending", max_length=32)),
                ("attempts", models.PositiveIntegerField(default=0)),
                ("received_at", models.DateTimeField(default=django.utils.timezone.now)),
                ("processed_at", models.DateTimeField(blank=True, null=True)),
                ("last_error", models.TextField(blank=True)),
            ],
            options={
                "verbose_name": "Lark Event",
                "verbose_name_plural": "Lark Events",
                "db_table": "lark_events",
                "ordering": ("-received_at",),
            },
        ),
        migrations.CreateModel(
            name="LarkSyncRun",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True, verbose_name="Created At")),
                ("updated_at", models.DateTimeField(auto_now=True, verbose_name="Last Modified At")),
                ("created_by", models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="%(class)s_created_by", to=settings.AUTH_USER_MODEL, verbose_name="Created By")),
                ("updated_by", models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="%(class)s_updated_by", to=settings.AUTH_USER_MODEL, verbose_name="Last Modified By")),
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True, db_index=True)),
                ("deleted_at", models.DateTimeField(blank=True, null=True, verbose_name="Deleted At")),
                ("job_id", models.CharField(default=generate_lark_job_id, max_length=64, unique=True)),
                ("sync_type", models.CharField(choices=[("full", "Full"), ("incremental", "Incremental"), ("import", "Import")], default="full", max_length=32)),
                ("status", models.CharField(choices=[("pending", "Pending"), ("running", "Running"), ("succeeded", "Succeeded"), ("failed", "Failed")], db_index=True, default="pending", max_length=32)),
                ("users_seen", models.PositiveIntegerField(default=0)),
                ("users_created", models.PositiveIntegerField(default=0)),
                ("users_updated", models.PositiveIntegerField(default=0)),
                ("members_added", models.PositiveIntegerField(default=0)),
                ("members_deactivated", models.PositiveIntegerField(default=0)),
                ("users_skipped", models.PositiveIntegerField(default=0)),
                ("error", models.TextField(blank=True)),
                ("started_at", models.DateTimeField(blank=True, null=True)),
                ("completed_at", models.DateTimeField(blank=True, null=True)),
                ("workspace", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="lark_sync_runs", to="db.workspace")),
            ],
            options={
                "verbose_name": "Lark Sync Run",
                "verbose_name_plural": "Lark Sync Runs",
                "db_table": "lark_sync_runs",
                "ordering": ("-created_at",),
            },
        ),
        migrations.CreateModel(
            name="LarkNotificationOutbox",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True, verbose_name="Created At")),
                ("updated_at", models.DateTimeField(auto_now=True, verbose_name="Last Modified At")),
                ("created_by", models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="%(class)s_created_by", to=settings.AUTH_USER_MODEL, verbose_name="Created By")),
                ("updated_by", models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="%(class)s_updated_by", to=settings.AUTH_USER_MODEL, verbose_name="Last Modified By")),
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True, db_index=True)),
                ("deleted_at", models.DateTimeField(blank=True, null=True, verbose_name="Deleted At")),
                ("event_key", models.CharField(db_index=True, max_length=255, unique=True)),
                ("message_type", models.CharField(max_length=64)),
                ("payload", models.JSONField(default=dict)),
                ("status", models.CharField(choices=[("pending", "Pending"), ("sending", "Sending"), ("sent", "Sent"), ("failed", "Failed"), ("dead", "Dead"), ("skipped", "Skipped")], db_index=True, default="pending", max_length=32)),
                ("attempts", models.PositiveIntegerField(default=0)),
                ("next_retry_at", models.DateTimeField(blank=True, null=True)),
                ("sent_at", models.DateTimeField(blank=True, null=True)),
                ("last_error", models.TextField(blank=True)),
                ("notification", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="lark_outbox_items", to="db.notification")),
                ("recipient_user", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="lark_notification_outbox", to=settings.AUTH_USER_MODEL)),
                ("workspace", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="lark_notification_outbox", to="db.workspace")),
            ],
            options={
                "verbose_name": "Lark Notification Outbox",
                "verbose_name_plural": "Lark Notification Outbox",
                "db_table": "lark_notification_outbox",
                "ordering": ("created_at",),
            },
        ),
        migrations.AddIndex(
            model_name="larkevent",
            index=models.Index(fields=["status", "event_type"], name="lark_events_status_04a2e7_idx"),
        ),
        migrations.AddIndex(
            model_name="larkevent",
            index=models.Index(fields=["tenant_key", "received_at"], name="lark_events_tenant__c46210_idx"),
        ),
        migrations.AddIndex(
            model_name="larksyncrun",
            index=models.Index(fields=["workspace", "status"], name="lark_sync_r_workspa_eeee17_idx"),
        ),
        migrations.AddIndex(
            model_name="larksyncrun",
            index=models.Index(fields=["sync_type", "created_at"], name="lark_sync_r_sync_ty_98b992_idx"),
        ),
        migrations.AddIndex(
            model_name="larknotificationoutbox",
            index=models.Index(fields=["status", "next_retry_at"], name="lark_notifi_status_88d11e_idx"),
        ),
        migrations.AddIndex(
            model_name="larknotificationoutbox",
            index=models.Index(fields=["workspace", "recipient_user"], name="lark_notifi_workspa_05bbbe_idx"),
        ),
    ]
