# Generated by Codex on 2026-06-12

import uuid

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("db", "0122_lark_integration_models"),
    ]

    operations = [
        migrations.CreateModel(
            name="LarkWorkspaceMemberExclusion",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True, verbose_name="Created At")),
                ("updated_at", models.DateTimeField(auto_now=True, verbose_name="Last Modified At")),
                (
                    "created_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(class)s_created_by",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Created By",
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(class)s_updated_by",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Last Modified By",
                    ),
                ),
                (
                    "id",
                    models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True, db_index=True),
                ),
                ("deleted_at", models.DateTimeField(blank=True, null=True, verbose_name="Deleted At")),
                (
                    "reason",
                    models.CharField(
                        choices=[("manual_removed", "Manual removed"), ("member_left", "Member left")],
                        default="manual_removed",
                        max_length=32,
                    ),
                ),
                ("is_active", models.BooleanField(db_index=True, default=True)),
                ("excluded_at", models.DateTimeField(default=django.utils.timezone.now)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="lark_workspace_member_exclusions",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "workspace",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="lark_member_exclusions",
                        to="db.workspace",
                    ),
                ),
            ],
            options={
                "verbose_name": "Lark Workspace Member Exclusion",
                "verbose_name_plural": "Lark Workspace Member Exclusions",
                "db_table": "lark_workspace_member_exclusions",
                "ordering": ("-excluded_at",),
            },
        ),
        migrations.AddIndex(
            model_name="larkworkspacememberexclusion",
            index=models.Index(fields=["workspace", "is_active"], name="lark_worksp_workspa_1b9c36_idx"),
        ),
        migrations.AddIndex(
            model_name="larkworkspacememberexclusion",
            index=models.Index(fields=["user", "is_active"], name="lark_worksp_user_id_628c48_idx"),
        ),
        migrations.AddConstraint(
            model_name="larkworkspacememberexclusion",
            constraint=models.UniqueConstraint(
                condition=models.Q(deleted_at__isnull=True, is_active=True),
                fields=("workspace", "user"),
                name="lark_member_exclusion_unique_active_workspace_user",
            ),
        ),
    ]
